### ISSUE TITLE
您好,依云,请问Github是不是关闭里issues之间关联的功能?

### ISSUE THREAD

**Issue by wsdjeg** [lilydjwg/dotvim#4]
记得上周之前,当我将一个ISSUES的url复制到另外一个别人的issues是,会在该评论下方出现一个提示,类似与关闭 和reopen一样的提示,用来提示复制的url所对应的issues状态的,请问该功能是不是被取消了?

**Comment by lilydjwg** [comment]
Test: https://github.com/jlord/sheetsee.js/issues/26

**Comment by lilydjwg** [comment]
刚测试了一下，没有取消呀。

**Comment by wsdjeg** [comment]
你好,可以截图看看么 我现在来复制一个 
https://github.com/drmingdrmer/xptemplate/issues/73

**Comment by wsdjeg** [comment]
![2015-09-08 23-47-30](https://cloud.githubusercontent.com/assets/13142418/9739844/345f58de-5684-11e5-89bb-038e16cb7c83.png)

**Comment by wsdjeg** [comment]
我这边并没有提示别人issues的状态

**Comment by lilydjwg** [comment]
你点过去就有了啊。

**Comment by wsdjeg** [comment]
非常感谢,最近才开始玩这个git,不是很懂.

**Comment by lilydjwg** [comment]
这是 GitHub 的功能，和 git 无关。

**Comment by wsdjeg** [comment]
恩.明白了,谢谢你啦,其实我能来github真的是太机缘巧合了,从来没有人跟我说过.我一直喜欢折腾ubuntu,后来玩vim,一开始插件都是手动配置,后来接触了最早的bundle,才来到了这个上面,找到很多实用的插件.而且发现很多人都很无私的把写出来的东西分享出来

**Comment by lilydjwg** [comment]
分享可不是因为无私，而是因为共贏——当大家都这么做时，可以促进交流，减少重复劳动，也让别人能够给出建议。当然还有荣誉感和成熟感。

**Comment by wsdjeg** [comment]
确实是的,最近我重新学习java,虽然以前学习过,但是感觉基础不够,想把后面的框架学写了,另外再学习点脚本语言.由于目前不是做这行工作的,所以实际操作的机会很少,一直向在这个上面弄一个小项目却不知道该如何着手

**Comment by Shawkyhassan** [comment]
Gffgutf jfftuf iuutfgv

**Comment by Aliya-halldjfjrkr** [comment]
> 确实是的,最近我重新学习java,虽然以前学习过,但是感觉基础不够,想把后面的框架学写了,另外再学习点脚本语言.由于目前不是做这行工作的,所以实际操作的机会很少,一直向在这个上面弄一个小项目却不知道该如何着手

**Comment by Aliya-halldjfjrkr** [comment]
#10

**Comment by wsdjeg** [comment]
无法登陆github,似乎邮件也无法退订。

**Comment by lilydjwg** [comment]
@wsdjeg GMail 网页界面，点击收件人右边的小箭头，有退订链接。邮件客户端的话，查看邮件头/邮件原文，在 List-Unsubscribe 头里有退订用的邮件地址。

**Comment by wsdjeg** [comment]
亲测无法退订，还是要求登录github账号。



***@***.***
 
发件人： 依云
发送时间： 2023-10-01 15:26
收件人： lilydjwg/dotvim
抄送： Eric Wong; Mention
主题： Re: [lilydjwg/dotvim] 您好,依云,请问Github是不是关闭里issues之间关联的功能? (#4)
@wsdjeg GMail 网页界面，点击收件人右边的小箭头，有退订链接。邮件客户端的话，查看邮件头/邮件原文，在 List-Unsubscribe 头里有退订用的邮件地址。

**Comment by 1587rt-cell** [comment]
> 记得上周之前,当我将一个ISSUES的url复制到另外一个别人的issues是,会在该评论下方出现一个提示,类似与关闭 和reopen一样的提示,用来提示复制的url所对应的issues状态的,请问该功能是不是被取消了?
