### ISSUE TITLE
你好 依云,我想实现这样一个功能,不知道你还能帮帮忙,谢谢!

### ISSUE THREAD

**Issue by wsdjeg** [lilydjwg/dotvim#5]
https://github.com/wsdjeg/DotFiles/blob/master/vimrc_neobundle
这个是我的vimrc,我希望在最后的一组映射在java的注释中不起作用,也就是说当前行前面除去空白不是//,那么就启用映射,如果是//就禁用映射,请问这样的功能能否实现

**Comment by lilydjwg** [comment]
能啊， `:help synIDattr`.

**Comment by wsdjeg** [comment]
我已经实现了,谢谢 并且已经提交PR

**Comment by wsdjeg** [comment]
你好 依云, 我尝试了下YCM 发现它真对太好用了,可以在词语前后 中间 都可以不全 另外对注释识别对也很好,也可以自动调用onmi! 但是你说对neocomplete我还没有尝试,据说需要lua支持,我的vim没有这个功能!

**Comment by lilydjwg** [comment]
装个支持的呗。

**Comment by wsdjeg** [comment]
你好，之前提到的功能，我已自己实现了，search函数，我看到你有一个vimcn的组织，有兴趣搞个vim相关项目，支持JAVA jsp android吗？

**Comment by lilydjwg** [comment]
我对 Java 没有兴趣。不过你如果需要的话，我可以给你 vimcn 组织的权限以及子域名什么的。

**Comment by wsdjeg** [comment]
那太好了,很乐意加入

**Comment by lilydjwg** [comment]
咦，原来有个叫 vimcn 的组织……我有的那个是 vim-cn，多了个横线呢。

**Comment by Firef0x** [comment]
@lilydjwg 您好！

我知道 vimcn 组织是做 Vim 及插件文档翻译的，但是一直很好奇 vim-cn 组织是干嘛的？好像只有一个聊天室和一个 Pastebin 的样子？ :fearful:

**Comment by lilydjwg** [comment]
嗯，vim-cn 最早就是一聊天室……后来弄了 XMPP 服务器、图床、pastebin。没了。也没什么人了。
