### ISSUE TITLE
是否可以让vim-cn更活跃一些。

### ISSUE THREAD

**Issue by wsdjeg** [lilydjwg/dotvim#6]
希望加入这个组织，同时我们可以搞一些线下活动，前段时间看了VIM-JP的线下讲座，做的很不错。不知道你是否有兴趣，如果平时比较忙，我想我很乐意来打点一下。

**Comment by wsdjeg** [comment]
http://vimconf.vim-jp.org/

**Comment by lilydjwg** [comment]
你想做什么就做吧。我手里有 vim-cn.com 的域名、GitHub 组织，以及 Google Groups 邮件列表。需要什么可以和我说，但是我是没有多少精力可以用于具体的事务了。

**Comment by wsdjeg** [comment]
如果可以的话，先开一个仓库，来做主页

**Comment by wsdjeg** [comment]
@lilydjwg 你好，请问我是否可以加入VIM-CN,我想讲一些不错的教程翻译出来推到里面去，谢谢

**Comment by lilydjwg** [comment]
@wsdjeg 邀请你了。

**Comment by wsdjeg** [comment]
非常感谢

**Comment by wsdjeg** [comment]
@lilydjwg 真不好意思呀,我删除错了组织,本来想删除vimcn的,结果把这个vim-cn给删除了.

**Comment by wsdjeg** [comment]
@lilydjwg 你好，我目前在做这样一个项目，Github-api.vim, 就是通过viml实现github的API. 但是由于目前精力有限，开发速度很慢，而且对于写文档，我很不擅长，不知道是否可以在社区里了解下，是否有人对此项目有兴趣，一起来做。
另外 我看了vim-jp 这个组织，确实非常活跃，也希望vim-cn同样如此。但是得要有人带头做些项目。

**Comment by lilydjwg** [comment]
可惜随着 Google Talk 的退出以及墙的加高，vim-cn 并没有多少人了，除了域名和 GitHub 组织也没什么东西了 QAQ

我现在很忙 TAT

**Comment by wsdjeg** [comment]
中国,真的感觉很悲哀,在国内搞IT都很忙.目前看到比较活跃的,就只有vim的qq群跟archlinux-cn irc频道.而qq群水的已经没底线了.
我现在是懒得再用qq群, v2ex也变味了,我也不用了.

**Comment by sk1418** [comment]
@wsdjeg  vim相关的活跃的社区, 讨论等还是很多的吧, 不一定非得国内国外啊
vim_use@googlegroups.com
https://www.reddit.com/r/vim/
http://vi.stackexchange.com/

都活跃的一塌糊涂的
