### ISSUE TITLE
escallt.vim遇到一个问题

### ISSUE THREAD

**Issue by roachsinai** [lilydjwg/dotvim#9]
您好，我使用的是Manjaro Linux， Xfce桌面。

在使用您提供的escalt.vim，有很大的帮助但是遇到一个问题：vim打开文件之后，光标所在行的最后一个字符会被替换为`0`。并重新进入Normal模式。

这个问题在`xfce-terminal`中存在并可以复现，而在`konsole中`不存在。

`重现条件`：vimrc中的内容只有https://github.com/lilydjwg/dotvim/blob/master/plugin/escalt.vim 的内容即可以重现。

**Comment by lilydjwg** [comment]
我这里也有问题，但是现象不一样：进入 Vim 后第一个按键会被吃掉。

Vim 8.2.1844
xfce4-terminal 0.8.9.2-2

你的版本是？

**Comment by roachsinai** [comment]
```
gvim 8.2.1704-1
xfce4-terminal 0.8.9.2-1
```
> 进入 Vim 后第一个按键会被吃掉。

也有。

**Comment by roachsinai** [comment]
一开始通过排除使用的插件，发现插件skywind3000/vim-terminal-help导致了这个问题：https://github.com/skywind3000/vim-terminal-help/issues/28

然后看https://github.com/skywind3000/vim-terminal-help/blob/e6d408bcbb61638e770b72152ae49a2e81c558a9/plugin/terminal_help.vim#L384 部分的代码，感觉和escalt.vim印象很相似。就测试了只有escalt.vim发现导致同样的结果。

然后，如果插件skywind3000/vim-terminal-help和escalt.vim共存：

```
call plug#begin('~/.vim/plugged')
Plug 'skywind3000/vim-terminal-help'
call plug#end()
```

`escalt.vim`存放于.vim/plugin下，也是同样的结果，不过有个例外：删除插件https://github.com/skywind3000/vim-terminal-help/blob/e6d408bcbb61638e770b72152ae49a2e81c558a9/plugin/terminal_help.vim#L430 这一行的代码结果就是`第一个按键会被吃掉`。

**Comment by lilydjwg** [comment]
https://github.com/vim/vim/commit/a45551a53557dba98973fdb3ff737dea2fffcda3 is the first bad commit

**Comment by roachsinai** [comment]
xfce-terminal 在 https://github.com/vim/vim/pull/2126 的终端列表里么？

**Comment by lilydjwg** [comment]
复现条件类似于：

```sh
vim --clean -c 'set <M-P>=^[P' -c 'nmap <M-t> a'
```

P 之后的字符没影响，之前还存在有影响的字符。

**Comment by lilydjwg** [comment]
报告给了 Vim： https://github.com/vim/vim/issues/7135

**Comment by roachsinai** [comment]
感谢！
